name: Unity Packages Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        packagePath:
          - ${{ github.event.inputs.packagePath }}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - name: Check package version
        id: check_version
        run: |
          package_version=$(node -p "require('${{ matrix.packagePath }}/package.json').version")
          latest_version=$(npm view ${{ github.event.repository.name }}@${{ github.event.release.tag_name }} version)
          if [ "$package_version" != "$latest_version" ]; then
            echo "::set-output name=publish::true"
          else
            echo "::set-output name=publish::false"
          fi
      - name: Publish package
        if: ${{ steps.check_version.outputs.publish == 'true' }}
        run: npm publish ${{ matrix.packagePath }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
